---
dist: bionic

language: python
python:
  - "3.8"

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
# https://docs.travis-ci.com/user/common-build-problems/
env:
  - ANSIBLE_VERSION=latest

branches:
  only:
    - master
    - dev

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - pip install ansible-lint jmespath netaddr

script:
  # Check the role/playbook's syntax.
  - find tasks -name "*.yml" | xargs ansible-lint

  # Run the role/playbook with ansible-playbook.
  # Requires cloud environment variables set in Travis
  - cd tests
  - ./install_roles.sh
  - ./test.sh
