- name: Lookup ecs_id
  include: lookup.yml

- name: Send request to API (show ECS)
  uri:
    url: "{{ AUTH_URL_ECS }}/servers/{{ ecs_id }}"
    method: PUT
    body_format: raw
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'show.json.j2')|to_json }}"
  register: ecs
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: ecs.status == 200
  changed_when: false

- debug:
    msg: "{{ ecs }}"
